
# html lang
language: en

# main menu navigation
menu:
  home: /
  tags: /tags
  search: /search
  about: /about

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
# - /css/normalize.css
- //cdn.bootcss.com/pure/1.0.0/pure-min.css
- /css/microb.css

# scripts loaded in the end of the body
scripts:
- //cdn.bootcss.com/zepto/1.2.0/zepto.min.js
#- /js/microb.js